version: 2.1

orbs:
  buildevents: honeycombio/buildevents@0.0.1

executors:
  linuxgo:
    parameters:
    working_directory: /go/src/github.com/honeycombio/samproxy
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace

  build:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - checkout
            - buildevents/berun:
                bename: go_get
                becommand: go get -v -t -d ./...
            - buildevents/berun:
                bename: go_test
                becommand: go test -v ./...
            - buildevents/berun:
                bename: go_build
                becommand: go install -ldflags "-X main.Version=${CIRCLE_TAG:-unset}" ./...
            - buildevents/berun:
                bename: apt_get_update
                becommand: sudo apt-get -qq update
            - buildevents/berun:
                bename: apt_get_install
                becommand: sudo apt-get install -y build-essential rpm ruby ruby-dev
            - buildevents/berun:
                bename: gem_install
                becommand: sudo gem install fpm
            - buildevents/berun:
                bename: build_deb
                becommand: ./build-pkg.sh -v "${CIRCLE_TAG:-unset}" -t deb
            - buildevents/berun:
                bename: build_rpm
                becommand: ./build-pkg.sh -v "${CIRCLE_TAG:-unset}" -t rpm
            - run: |
                mkdir artifacts
                cp $GOPATH/bin/samproxy* artifacts
                find artifacts -ls
            - persist_to_workspace:
                root: artifacts
                paths:
                  - samproxy
                  - samproxy_${CIRCLE_TAG:-unset}_amd64.deb
                  - samproxy-${CIRCLE_TAG:-unset}-1.x86_64.rpm

  publish:
    docker:
      - image: cibuilds/github:0.12.1
    steps:
      - buildevents/with_job_span:
          steps:
            - attach_workspace:
                at: artifacts
            - run:
                name: "Publish Release on GitHub"
                command: |
                  echo "about to publish to tag ${CIRCLE_TAG}"
                  ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/samproxy

workflows:
  build:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
